### ISSUE TITLE
Column pattern for azure monitor data Source

### ISSUE THREAD

**Issue by NitishRayar** [yesoreyeram/yesoreyeram-boomtable-panel#106]
**What you are struggling with**
I want to show cpu, memory and disk utilization in table structure using azure monitor datasource

i'm not getting how to take multiple column in one table using azure data source and also not getting how to use column pattern in boom table.

i have tried for cpu and memory metrics in single table but not able to split for two table. Its showing like 

Duplicate matches

Help me split column like cpu,memory and also help me how to use pattern for individual column .

**Comment by yesoreyeram** [comment]
Have u checked https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/blob/master/README.md#azure-monitor-usage ?
