### ISSUE TITLE
[Help Required] Is it possible to have text in one of the columns 

### ISSUE THREAD

**Issue by orena1** [yesoreyeram/yesoreyeram-boomtable-panel#110]
**What you are struggling with**
Is it possible that one of the columns in a table will be text-based?
like this:
![image](https://user-images.githubusercontent.com/8983713/68255365-ac2b3180-0035-11ea-9baf-2bc2595320a4.png)

**What you tried**

I tired saving text in the Influx DB, but then I got in the table - no data or

**Comment by skaarup1986** [comment]
Same problem for me.

**Comment by yesoreyeram** [comment]
No.. only timeseries values are supported.

**Comment by zakaryanla** [comment]
Same problem for me.
