### ISSUE TITLE
[Bug] Title 

### ISSUE THREAD

**Issue by biohazardxxx** [yesoreyeram/yesoreyeram-boomtable-panel#114]
**Describe the bug**
The filter option with two patterns does not hide when only one condition is true (like an OR condition). IT only hides rows if both filters match.
I understand this function to hide the entire row if any of the pattern values matches the filter.
As from the docs: "If your output have more rows and if you require to hide certain rows based on their output value, you can use the filter option to hide those rows."
Maybe this is intended behavior? If so it would be good to make this more clear in the docs but maybe also add an option to make the filters OR/AND in options tab.

**Screenshots**
Page count pattern set "Hide if value is below" to 1000
![image](https://user-images.githubusercontent.com/1370362/68840245-a0d5a700-06c2-11ea-8416-b3aff6dcda80.png)
Fragmentation pattern set "Hide if value is below" to 15
![image](https://user-images.githubusercontent.com/1370362/68840322-cb276480-06c2-11ea-9195-01f36105fc49.png)

**Version Details:**
 - Grafana version : 6.4.3
 - Plugin version : 1.3.0

**Additional context**
Let me know if anything more needed

**Comment by yesoreyeram** [comment]
Hi. This is the expected behavior. Cells will be hidden only if all the siblings in the row met the hidden = true condition. 

Docs may need update to mention that clearly.
