### ISSUE TITLE
[Bug] Doesn't work with Grafana 6.5.0

### ISSUE THREAD

**Issue by Mackan93** [yesoreyeram/yesoreyeram-boomtable-panel#116]
**Describe the bug**
When viewing any boomtable panel in Grafana version 6.5.0, I get the error `_this.$sce is undefined` and the panel is blank, i.e none of our boomtable panels are currently working.

**Version Details:**
 - Grafana version : 6.5.0
 - Plugin version : 1.30

**Comment by turbatus** [comment]
I confirm, after upgrading to 6.5.0 the plugin stops working.
![image](https://user-images.githubusercontent.com/8330709/69706877-e9e11e80-10f8-11ea-9398-27fa329bb70d.png)

**Comment by dev-deeper** [comment]
I got same error ```_this.$sce``` with ```Grafana v6.5.0 (commit: 24a5d2f)``` and plugin ```v 1.3.0```.

**Comment by yesoreyeram** [comment]
grafana confirmed that this is a generic issue and nothing to do with the plugin. Grafana team fixex this via https://github.com/grafana/grafana/issues/20662 . So you may need to upgrade grafana once new version available.

**Comment by Mackan93** [comment]
I can confirm that the issue now is resolved in Grafana v 6.5.1.
