### ISSUE TITLE
[Bug] Plugin completely nonfunctional in Grafana 6.5

### ISSUE THREAD

**Issue by calebsmac** [yesoreyeram/yesoreyeram-boomtable-panel#117]
**Describe the bug**
Upon upgrading to Grafana 6.5, we get the following any time a BoomTable pulls data:

TypeError: Cannot read property 'trustAsHtml' of undefined

**Screenshots**
<img width="273" alt="Screen Shot 2019-12-02 at 12 56 49 PM" src="https://user-images.githubusercontent.com/26824617/69983029-bf7dcf80-1503-11ea-8d06-0502e68c810c.png">

**Version Details:**
 - Grafana version : 6.5.0
 - Plugin version : 1.3.0

**Additional Context**
BoomTable plugin was working just fine prior to the update.

**Comment by calebsmac** [comment]
I just noticed that a new version of this plugin was recently released. We will try updating our plugin version as soon as possible to determine if that resolves the issue.

**Comment by yesoreyeram** [comment]
Duplicate issue https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/issues/116 use 6.5.1
