### ISSUE TITLE
Allow characters other than numbers, text for example

### ISSUE THREAD

**Issue by egorky** [yesoreyeram/yesoreyeram-boomtable-panel#134]
**Is your feature request related to a problem? Please describe.**
Yes, I want to display IP addresses but they are formated as text (not number) and the Boom Table doesn't support it even though they are in a time series format.

**Describe the solution you'd like**
I would like the Boom Table to be able to accept values other than numbers.

**Describe alternatives you've considered**
I've tried to get the text but to no avail

**Additional context**
With numbers, the table works nice.

**Comment by danielpereira-gub** [comment]
any return?

**Comment by egorky** [comment]
not to my knowledge.

**Comment by yesoreyeram** [comment]
As far as I can think, this feature won't be available anytime soon unless someone opens PR.

**Comment by egorky** [comment]
ok, got it.
