### ISSUE TITLE
[Help Required] Release to https://grafana.com/grafana/plugins/yesoreyeram-boomtable-panel

### ISSUE THREAD

**Issue by axelrtgs** [yesoreyeram/yesoreyeram-boomtable-panel#138]
The later versions of this plugin have not been released to https://grafana.com/grafana/plugins/yesoreyeram-boomtable-panel

Would it be possible to get it released officially so we can easily download the latest version using the grafana-cli

**Comment by yesoreyeram** [comment]
https://github.com/grafana/grafana-plugin-repository/pull/667 should fix this
