### ISSUE TITLE
[Help Required] Changing labels when being on top of a value

### ISSUE THREAD

**Issue by hadarizi** [yesoreyeram/yesoreyeram-boomtable-panel#139]
Hi,
I tried without success to change the label & values when being on top of warning value (4) into a list of which machines have alerts + alert name / description ( see attachment).

![image](https://user-images.githubusercontent.com/47101913/85404169-3d203000-b567-11ea-9906-ee015a88671a.png)

Same as in zabbix, when the mouse is over the value:
![image](https://user-images.githubusercontent.com/47101913/85404487-aa33c580-b567-11ea-9d0b-348b503a2d23.png)

**Comment by yellowpattern** [comment]
You need to use the Tooltip Template for this.

In the Visualization panel for your graph, you will have some patterns. Each pattern will have its own "Tooltip Template". You need to set this.
![Screen Shot 2020-06-24 at 8 41 33 am](https://user-images.githubusercontent.com/24280758/85473410-88cdea80-b5f6-11ea-8a94-487e2903fe38.png)

**Comment by hadarizi** [comment]
@yellowpattern Thanks for you quick response!
Is there any way to view the alerts description the same way as in zabbix (hostname & alertname - see the attachment above).
I'm having issues to view more than 1 alert description due to 'duplicate matches'

**Comment by yellowpattern** [comment]
Alerts are managed differently in grafana. You manage them from the "Alerts" panel when editing it.
