### ISSUE TITLE
[Help Required] Is Boom Table compatible with Alertmanager Datasource?

### ISSUE THREAD

**Issue by sakishrist** [yesoreyeram/yesoreyeram-boomtable-panel#142]
I tried using the alertmanager datasource plugin with a boom table for the ability to have more colours. I couldn't find though any information on how or if these two are compatible. From what I see the alertmanager returns json, but I don't know if the boom table sees json on its input.

I tried the debug option but that does not give me any data at all. The debug table at the top is empty.

The version of grafana is **6.4.0**
Version of Boom Table: **1.3.0**

**Comment by yesoreyeram** [comment]
As per the documentation, Boom Table supports only timeseries results. It doesn't know how to handle JSONs yet.

![image](https://user-images.githubusercontent.com/153843/87531611-d97eb380-c689-11ea-9d3b-df4f67b0ba00.png)
