### ISSUE TITLE
[Help Required] Total SUM of columns

### ISSUE THREAD

**Issue by germio** [yesoreyeram/yesoreyeram-boomtable-panel#144]
**What you are struggling with**

Hi Is it possible to do a calculation between columns
Column1 + Column2 = ColumnTotal

**Comment by yesoreyeram** [comment]
No. This is not possible and no plans to implement in short term. 

Once the plugin is compatible with Grafana 7 transform feature, that can be achieved with that.

**Comment by germio** [comment]
Thanks for the update
