### ISSUE TITLE
Hi.   Support for Grafana version issues

### ISSUE THREAD

**Issue by xiaolongli827** [yesoreyeram/yesoreyeram-boomtable-panel#159]
I installed version 1.4 of the BoomTable plugin in Grafana, it shows support for 7.0, but your documentation supports 6.0. I want to know if the latest stable version 1.4 of BoomTable supports Grafana 7.0. Is your document not updated?

**Comment by xiaolongli827** [comment]
I want to know if the latest stable version of BoomTable plugin supports Grafana 7.0

**Comment by xiaolongli827** [comment]
I want to know if the latest stable version of BoomTable plugin supports Grafana 7.4.5

**Comment by andrewmeyer** [comment]
I am running Boom Table 1.4.0 in grafana 7.0.3 without issue, but cannot say if it works on later versions.

**Comment by yesoreyeram** [comment]
This works with 7.4.5 version. ( but not all the cases tested ). Report if you see any issues.
