### ISSUE TITLE
Boom Table plugin Disabled due to missing Signature

### ISSUE THREAD

**Issue by shawn3231** [yesoreyeram/yesoreyeram-boomtable-panel#169]
**Describe the bug**
Boom Table plugin Disabled due to missing Signature. Would like a signed version as soon as possible so that we don't have to work around this issue. Thank you

**Version Details:**
 - Grafana version : 8.3.3
 - Plugin version : 1.4.1
 - Did this work in any other version of Grafana : Yes, 7.x.x

**Screenshots**
![image](https://user-images.githubusercontent.com/49657262/146053165-e48d0968-d28a-40ef-9058-4889cfaa88d0.png)

**Comment by yesoreyeram** [comment]
Was it working with 8.3.2 grafana for you? I have multiple instances of boom table with 8.3.2 without any issues and the plugin is of course signed in the grafana catalog.

**Comment by shawn3231** [comment]
We just upgraded, from 7.x.x (I can't remember the exact version, just that it was in the 7 range) and now it has been updated to 8.3.3 and that is what our server reported that the plugin was missing it's signature.

**Comment by shawn3231** [comment]
I did look up and see that Boom Theme reports as signed.
![image](https://user-images.githubusercontent.com/49657262/146060453-08920206-a653-4f2b-90b3-e9a4799318a9.png)

**Comment by shawn3231** [comment]
OK, Sorry it appears the server had duplicate packages and was pulling the information from an old 1.0.1 package. It is now working on our end.
![image](https://user-images.githubusercontent.com/49657262/146061549-69c6dcdc-0d88-46e9-860e-62e8d1e0bf00.png)
