### ISSUE TITLE
[Bug] Error while rendering panel as image

### ISSUE THREAD

**Issue by usmanC9** [yesoreyeram/yesoreyeram-boomtable-panel#18]
Getting error while rendering boomtable as image in grafana.

**Comment by yesoreyeram** [comment]
Hi @usmanC9 , Could you share the details of the error with some screenshot?

**Comment by usmanC9** [comment]
Hi,
I have created a dashboard which include boomtable. The table is created successfully but when i share the boomtable as an image, the grafana server gives me timeout error.

![screencapture-192-168-100-18-3000-render-d-solo-x56lgxrik-customer-summary-report-2018-03-13-16_13_06](https://user-images.githubusercontent.com/17683147/37341944-9a1646da-26dc-11e8-8c22-bc54dacd4928.png)

**Comment by usmanC9** [comment]
boomtable panel in dashbaord

![capture2](https://user-images.githubusercontent.com/17683147/37342254-730583a2-26dd-11e8-956d-8c345dbcff6d.PNG)

**Comment by yesoreyeram** [comment]
Grafana issue https://github.com/grafana/grafana/issues/11180 also talks about similar issue.

**Comment by marefr** [comment]
@usmanC9 are you running Grafana behind a reverse proxy, like apache or nginx? Have you tried changing the &timeout url parameter? Is your panel in a collapsed row? Please include the full render url that is failing so that we can investigate this further.

**Comment by yesoreyeram** [comment]
@usmanC9 could you try this with grafana 5.0.2?

**Comment by usmanC9** [comment]
@marefr no grafana is not running behind any reverse proxy. I have also performed changes but no luck. 
full url : http://172.30.2.11:3000/render/dashboard-solo/db/customer-summary-report?orgId=1&var-customer=PGC&var-location=All&var-device=All&panelId=13&from=1521093014282&to=1521114614282&width=1000&height=500&tz=UTC%2B04%3A00

@yesoreyeram i will try with 5.0.2 and get back to you.

**Comment by yesoreyeram** [comment]
5.0.2 also issue exists. I feel like this is a bug in grafana. rendering image doesnt work in any of the third party plugins for me.  I will investigate further open a ticket with grafana,

**Comment by deedrah** [comment]
If you look at https://github.com/grafana/grafana/blob/master/tools/phantomjs/render.js you will see that it is checking `window.panelsRendered`. It looks like it should be incremented by calling this method https://github.com/grafana/grafana/blob/master/public/app/features/panel/panel_ctrl.ts#L61 (https://github.com/grafana/grafana/blob/master/public/app/core/profiler.ts)

All plugins provided by grafana calls it https://github.com/grafana/grafana/search?q=renderingCompleted&unscoped_q=renderingCompleted

**Comment by hardik2408** [comment]
I am using boom tables in my dashboards and using this [reporter](https://github.com/IzakMarais/reporter) to generate pdf reports. I am facing the same issues as listed here. 
I am not using a reverse proxy, I have tried changing the timeout parameter and my panel is not inside a collapsed row. 
**Grafana Version:** 6.7.3
**Boom Table Version:** 1.3.0

**Comment by amotl** [comment]
Dear @yesoreyeram,

first things first: Thanks a bunch for conceiving this fine Grafana Plugin. We are using it within the [Hiveeyes Project](https://hiveeyes.org/) on our data acquisition server [1].

When trying to render it as an image, we are running into the same issues as outlined within this issue, see [2].

I believe it can be mitigated by placing a call to `renderCompleted()` appropriately, see [3]. Is there anything you could do about this?

Thanks already for looking into this!

With kind regards,
Andreas.

[1] https://swarm.hiveeyes.org/
[2] https://community.hiveeyes.org/t/rendering-beim-grafik-export-von-boom-table-panels-geht-nicht/3282
[3] https://community.grafana.com/t/custom-plugin-unable-to-render-image-from-share-panel-link/5263
