### ISSUE TITLE
Do not replace tokens that are in the actual datasource name

### ISSUE THREAD

**Issue by xkilian** [yesoreyeram/yesoreyeram-boomtable-panel#31]
For the following metric in graphite format
switch1.interface1_2_3.ifAdminStatus

If selecting _1_ as the row name, the pattern _2_ will be detected and the row name will end up as:
switch1.interface1**ifAdminStatus**3
This is not a desired feature. The plugin should not do recursion of token replacement. (Where _2_ is a token)

Either permit changing the the special caracters for the plugin token underscore in this case. Or do not do token replacement in the actual data source name values!

This issue is most common for network equipment, which is also one of the best use cases of the boom table. :-/

**Comment by yesoreyeram** [comment]
Hi @xkilian Thanks for reporting the issue. I can't change the current behaviour as it might break existing installations. But, I will provide option to override replace tokens. Hopefully, I will release a fix by end of this week.

**Comment by xkilian** [comment]
Very nice, I look forward to testing your changes. In the mean time, I have modified manually the code to change the token to something that is non conflicting with my datasources, but this is not optimal. :-)
(my underscores where transformed into italic formating, but I think you understood my meaning.

**Comment by yesoreyeram** [comment]
@xkilian . I have committed required changes in master branch. Please test and provide feedback.

**Comment by xkilian** [comment]
Works for me, thank you.
