### ISSUE TITLE
Supporting dashboards links and search 

### ISSUE THREAD

**Issue by JosephFY** [yesoreyeram/yesoreyeram-boomtable-panel#32]
first, thank you for the great panel. We have been searching for a replacement for the regular built-in table panel that can show multiple metrics within the same panel.

There is 2 things that holding us from using this panel. So we were wondering to suggest those as enhancements be added at some point.

1. Having the ability to link to different dashboards 

![image](https://user-images.githubusercontent.com/28739923/43875816-c018991a-9b57-11e8-87ff-ae3328d413b2.png)

2. the ability to search inside the panel content with just like the screenshot below (attached screenshot is from the datatable  panel)

![image](https://user-images.githubusercontent.com/28739923/43875979-9343e182-9b58-11e8-9088-f8b24fb1715b.png)

Appreciate the help.

**Comment by xkilian** [comment]
Great suggestion for the links. Having a cell clickable for drill-down would make this plugin even more flexible. If links are implemented, please aim to be compatible with dashboard variables.

**Comment by yesoreyeram** [comment]
Hi @JosephFY Thanks for the suggestion. 

Suggestion 1 : It is pending from my side for the long time. I will consider this as my next priority. It is one of the big feature in my list ("Clickable cells"). But expect only by mid of October as i will on vacation for next few weeks.

Suggestion 2 : We don't require the search feature right now, as this is only applicable if pagination is supported. I will consider this option if pagination is implemented in future.

Feel free to send pull requests, if possible.

**Comment by yesoreyeram** [comment]
@JosephFY @xkilian - Clickable links are available in master now

https://github.com/yesoreyeram/yesoreyeram-boomtable-panel#table-cell-links

![image](https://user-images.githubusercontent.com/153843/48318359-5b862180-e5f7-11e8-9e9f-a75c8c33f694.png)

**Comment by JosephFY** [comment]
Thank you very much. This is awesome
