### ISSUE TITLE
[Feature Request] Sort function in table header 

### ISSUE THREAD

**Issue by jehutywong** [yesoreyeram/yesoreyeram-boomtable-panel#33]
It would be nice to support sort in column headers.

**Comment by skilxnTL** [comment]
May I ask when will sort function be supported? Thanks 😄

**Comment by yesoreyeram** [comment]
I am happy to merge if someone contribute to this. I may some time later this month if no contributions received.

**Comment by NivAmat** [comment]
I'll also be glad to have this ability.

Thanks for the great plugin!

**Comment by skilxnTL** [comment]
I never use TypeScript. So it may take too much time for me to implement it. But if I have time, I will try it.

**Comment by NivAmat** [comment]
hey,
so I tried to implement this, but I encounter 1 major problem - the headers are being generated in runtime, without letting the angular infrastructure build those new html tags, means you can't add "ng-click" to those header tags.

I'm referencing to the file: src\app\app.ts
in lines 81 and 84:
line 81:
`output.headers += <th style="padding:4px;text-align:${options.text_alignment_firstcolumn}" ng-click="ctrl.sort()">${default_title_for_rows}</th>;`

line 84:
`output.headers += <th style="padding:4px;text-align:${options.text_alignment_header}" ng-click="ctrl.sort()">${c}</th>;`

so I tried to add ng-click, but the angular doesn't recognize that tag because that new html-tag isn't being built again. though if I'll change it to onclick - it will work, but it won't recognize ctrl object, means I can't use any angular object, which makes it impossible to implement with onclick.


any solution for that?

the rest of the feature I can implement in less than a day

**Comment by NivAmat** [comment]
@yesoreyeram
I've implemented the sort function, I just need an answer to my question above to be able to send a pull request

Please assist :)

**Comment by yesoreyeram** [comment]
@NivAmat Glad to see you trying to solve this. I feel that `ng-click` should work. But i haven't tried yet. If that really doesn't work, HTML part can be moved to HTML template. Give a try and let me.  I will try once I find time. Thanks BTW.

**Comment by yesoreyeram** [comment]
Sorting is enabled in master branch with the following conditions

* By default values are not sorted
* If header cells are clicked, table will be sorted by asc / desc 
* Sorting is based on actual values. 
* Sorting is not persisted. 
* Not matching series always goes bottom.

Some examples given below. ( note the arrow in the header )

![image](https://user-images.githubusercontent.com/153843/54079844-49359f00-42dc-11e9-95c4-5c04424b569a.png)
![image](https://user-images.githubusercontent.com/153843/54079847-5488ca80-42dc-11e9-8052-f82f1cb8fb4c.png)
![image](https://user-images.githubusercontent.com/153843/54079849-5c486f00-42dc-11e9-9cf3-295341edbe9c.png)
![image](https://user-images.githubusercontent.com/153843/54079850-62d6e680-42dc-11e9-964a-d2822fb22b9f.png)

**Comment by yesoreyeram** [comment]
@nivamat if you can spend time , could you review my solution and let me know if you see any problems.

**Comment by NivAmat** [comment]
@yesoreyeram it looks good, but its not possible to also sort by the first column (possible to use a simple string comparator for this situation.. what do you think?)

**Comment by JosephFY** [comment]
@yesoreyeram and @NivAmat  Thank you for the effort to add this, can't tell you how important this is in our use case. Is there any way to have the Sorting persisted when saving the dashboard? Having this on big display screens and need certain values to be on the top when they change (like down devices will be colored red and will move on the top of the list) hard to go to all screens and change that every time the dashboard reloads or rotate on a playlist

> Sorting is not persisted.

**Comment by yesoreyeram** [comment]
@JosephFY  that is not a big change to implement. But want to make sure that sorting is working as expected.  That needs some testing.  We dont want any bugs introduced. 

Can you confirm if this works as expected for you?

**Comment by Bounzz** [comment]
Any news for that pr ?

**Comment by NivAmat** [comment]
@yesoreyeram We have tested the new feature and it seems to work just great.
The only concern is that it is not possible to sort by the first column (the index column)

**Comment by Bounzz** [comment]
When this feature will be available ?

**Comment by NivAmat** [comment]
@Bounzz I've implemented a fix for the above issue (the first column cannot be sorted).
I'll push it early next week.

**Comment by Bounzz** [comment]
Any news ?

**Comment by yesoreyeram** [comment]
This feature is already availbale in master branch. 

@Bounzz what you are expecing?

**Comment by Bounzz** [comment]
Sorry im not good with github.

How can i update the plugins ?

**Comment by yesoreyeram** [comment]
bbe0646e72ea4f0bdcaa8010b160e85fdcd30358 should help persistant sorting. Availble in latest master or from version 1.2.x
