### ISSUE TITLE
Not possible to change the order of patterns

### ISSUE THREAD

**Issue by Genluck** [yesoreyeram/yesoreyeram-boomtable-panel#34]
Hello.
Thank you very much for your panel. It is really a flexible add-on with reach functionality.

But I found one problem with current functionality: it is not possible to change order of created patterns. For example, if I would create patterns at this way:
![default](https://user-images.githubusercontent.com/24607544/44897137-52c5c500-ad03-11e8-8de4-9d5f0a7e4281.png)
As result the columns order would be look like this and it is not possible to change the order of them:
![default](https://user-images.githubusercontent.com/24607544/44897267-c798ff00-ad03-11e8-9fd2-950edd1ecdfc.png)
The only way to change the order of columns at this case is to change all rules of patterns.

Also it would be great if you could add (as additional feature) a support for text type of metrics (and as threshold a match for regex, string pattern or length of the string).

**Comment by yesoreyeram** [comment]
It is possible to change the order of the patterns. Use master branch / version 0.3.2.  You can see the options to clone/reorder the pattern. Please check and confirm

![image](https://user-images.githubusercontent.com/153843/45427031-bf42ab80-b695-11e8-9b25-9bd00d512819.png)
