### ISSUE TITLE
Support Prometheus as a source

### ISSUE THREAD

**Issue by xkilian** [yesoreyeram/yesoreyeram-boomtable-panel#35]
having looked at the code, the plugin is built to easily deal with the metric hierarchy of graphite. However, making the plugin more generic to support prometheus as well would be a great help. Prometheus has a lot of people using it. Might be something to think about. as dealing intelligently with labels might make support for graphite (with labels), prometheus and influx possible.

Cheers,
X

**Comment by yesoreyeram** [comment]
Sorry mate. With the current scope / design, this is not possible to support promeetheus. May be we will add this in future..

**Comment by yesoreyeram** [comment]
> Sorry mate. With the current scope / design, this is not possible to support promeetheus. May be we will add this in future..

Still there is a way to achieve the desired output. The following section of the README explains how to implement metrics from Prometheus datasource. 
https://github.com/yesoreyeram/yesoreyeram-boomtable-panel#prometheus-guidelines

![image](https://user-images.githubusercontent.com/153843/46359340-f4249b80-c660-11e8-9216-24bb1ed1c801.png)

Please feel free to reopen the issue if you feel that this is not the desired output

**Comment by yesoreyeram** [comment]
Hi @xkilian , Did you get a chance to test with Prometheus?

**Comment by xkilian** [comment]
Wow! I just noticed the updated plugin. I will certainly get this in our pipeline, as I absolutely love the boom table plugin. I have some urgent work that has to be completed, but I look forward to testing it. Cheers and congratulations on this plugin.
