### ISSUE TITLE
[Feature Request] Option to modify the font size

### ISSUE THREAD

**Issue by yesoreyeram** [yesoreyeram/yesoreyeram-boomtable-panel#47]
Option to modify the font size of the table will be helpful

**Comment by mykllterry** [comment]
Don't know if anyone else might find this useful (or if this is a good place to post this) But I've found this works for column names, row names, and cell contents

<font size="+2"> _fa-check,green_ </font>
or
<p style="font-size:14px; color:#538b01; font-weight:bold; font-style:italic;">
  _0_ 
  </p>

Using Grafana 6.1.3
BoomTable 1.0.0

**Comment by AdamSmith89** [comment]
Would like to second this. Font size is the only thing stopping me from rolling this out.

@mykllterry that didn't seem to work for the data I'm using. When I added the html tags to the "Row Name" it then caused the data in the Value column to be changed - it wasn't just the value anymore it contained all the data from the series.... It was pretty odd...

I'm using Grafana v6.2.4 which is newer than the version you posted. Any ideas?

**Comment by mykllterry** [comment]
I was able to recreate a similar sounding issue by removing the entry I have in the "Legend" section of the Query set up page.
If the legend was blank then I get a whole lot of rows added to the table.
If the legend did not include a tag I got a lot of undefined values in one row.

My Legend looks like
Server Success Rate | {{server name}}

**Comment by yesoreyeram** [comment]
@mykllterry  - font size modification option is now available in master or from version 1.3.  Feel free to test and let me know the feedback.

Could you create seperate issue for the blank legend with more details. ( FYI. the panel will look for metrics with some delimiter. Legend is one way of achieving this ).
