### ISSUE TITLE
Support clickable cell on the first column

### ISSUE THREAD

**Issue by jehutywong** [yesoreyeram/yesoreyeram-boomtable-panel#49]
Looks like cell links only enabled in the patterns page where I have no control of first column.

Am I missing something? Or the first column is not yet supported of this function. I am in version 0.5.1

Thanks

**Comment by yesoreyeram** [comment]
Sorry. First column clickable cells are not supported. Hopefully they will not be supported. Because multiple patterns can yield same row name but different links. If you have any idea how this can be implemented, please share
