### ISSUE TITLE
Elasticsearch support ?

### ISSUE THREAD

**Issue by parisnps** [yesoreyeram/yesoreyeram-boomtable-panel#51]
Is there a plan to support Elasticsearch ? I am sure lot of folks will benefit from it.

Thanks

**Comment by yesoreyeram** [comment]
The support is already there if you render metrics as timeseries. 

**No plans for table format metrics.** There is no necessity for hadling tables.

**Comment by yesoreyeram** [comment]
Feel free to reopen this if you have any specific usecase or notice any issue
