### ISSUE TITLE
Value field in tooltip doesn't respect units and decimals

### ISSUE THREAD

**Issue by adivinho** [yesoreyeram/yesoreyeram-boomtable-panel#53]
Values in drill-down from cells are ignoring format in an used pattern.
![screenshot_20181211_114406](https://user-images.githubusercontent.com/25184101/49801964-53371880-fd54-11e8-9d6b-ef6be32ce612.png)

**Comment by yesoreyeram** [comment]
Thanks for notifying this. Current master branch is having the fix. This will be part of 0.6.0 release

![image](https://user-images.githubusercontent.com/153843/49817138-61426480-fd67-11e8-9423-653e113af79c.png)
