### ISSUE TITLE
[Feature Request] Support variables in thresholds field

### ISSUE THREAD

**Issue by PhantomPhreak** [yesoreyeram/yesoreyeram-boomtable-panel#57]
I have a lot of metrics shown in the table, matching different patterns. If i want to change thresholds, i have to change it manually for each pattern.
If set thresholds using grafana variables, i have `NaN,NaN` as thresholds

Thanks!

**Comment by yesoreyeram** [comment]
Template variables are not supported currently. I will be working on that soon.
