### ISSUE TITLE
install the latest plugin version

### ISSUE THREAD

**Issue by arnitolog** [yesoreyeram/yesoreyeram-boomtable-panel#59]
As far as I can see the latest version which can be installed via grafana_cli is 0.4.6. Is it possible to install the latest one (0.5.0) via cli?

**Comment by yesoreyeram** [comment]
Not yet. 0.5.x is not merged with grafana plugin repo.  We are targettting major version upgrade 1.0.x ( https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/tree/v1 ) which will be expected to release by end of Jan

**Comment by arnitolog** [comment]
cool. thanks a lot.

**Comment by ClementPagesEole** [comment]
Hello,
Do you have some news about this release ?
When will it be available via grafana cli ?

**Comment by JosephFY** [comment]
@yesoreyeram Thank you for the awesome plugin

does the new version has the option of paging? we have some tables that return many values and having all those on the dashboard is making it lag. 

Another question, is the new version has an option to eliminate the N/A values as an option? we are facing the following issue:
let's say we have 10 servers, all 10 have availability metric but 8 of them has memory metric, we only want to show the 8 servers on the panel not 10 (cause the other two will show N/A for memory)

Thanks again

**Comment by yesoreyeram** [comment]
There is a pull request now pending with grafana. https://github.com/grafana/grafana-plugin-repository/pull/387 Once that is merged, v1.0.0 will be available through grafana.com and cli.

**Comment by arnitolog** [comment]
Cool! thanks a lot
