### ISSUE TITLE
Howto use label value as column value?

### ISSUE THREAD

**Issue by anthraxn8b** [yesoreyeram/yesoreyeram-boomtable-panel#62]
Hi!
I am pretty sure this will have been already discussed - but I did not find it. Sorry.

**question**
I would like to use a metric label value as a column value instead of the metric value.
Is it possible?

**example**

    dms_wmi__wmi_service_status{instance_code="ABC",name="processnamexyz",status="ok"} = 1

I would like to get something like:

name | status
------------ | -------------
ABC-processnamexyz | ok

and **NOT**:

name | status
------------ | -------------
ABC-processnamexyz | 1

THX for answering the - maybe already answerd - question :-)

**Comment by yesoreyeram** [comment]
You need to use the transform value method. 

https://github.com/yesoreyeram/yesoreyeram-boomtable-panel#value-transformation-based-on-thresholds

To use this, You may need to format your query legend in such a way that it return some key in delimited form. Below example, the query returned in `|` delimited. ( From the query, i assume you use prometheus )

In the metrics tab

**Query** `dms_wmi__wmi_service_status{instance_code="ABC",name="processnamexyz",status="ok"}`
**Legend Format**  `dms_wmi__wmi_service_status | {{instance_code}} | {{name}} | {{status}}`

In the patterns tab

You may need to set the delimiter as `|` and then refer your status field as `_3_` in your value transform field

Some more example

![image](https://user-images.githubusercontent.com/153843/52684781-4f379a80-2f3f-11e9-8ada-fd357045ab4a.png)

![image](https://user-images.githubusercontent.com/153843/52684792-5a8ac600-2f3f-11e9-9435-83d0727fbe2c.png)

![image](https://user-images.githubusercontent.com/153843/52684856-8dcd5500-2f3f-11e9-9743-906e70ac33f4.png)

Hope this helps.

**Comment by rodrigolemenunes** [comment]
Hi,
I tried to use the "Transform Values for thresholds" with field delimited, but it doesn´t work.
Did I do something wrong?
The variables _row_name_ , _col_name_ and _value_ work.
Version: 0.5.1


![image](https://user-images.githubusercontent.com/47793907/53042805-df0ca580-3465-11e9-977e-e6d0d1d6739f.png)

**Comment by yesoreyeram** [comment]
Have u set thresholds?

**Comment by rodrigolemenunes** [comment]
Even setting thresholds has the same effect. In this case returned first position from Transform Values .

**Comment by yesoreyeram** [comment]
Sorry. It seems value transform is broken in the recent versions.

**Comment by yesoreyeram** [comment]
Sorry. It seems value transform [doesn't implement](https://github.com/yesoreyeram/yesoreyeram-boomtable-panel#value-transformation-based-on-thresholds) this yet. My bad memory.

Currently value transform only supports  `_value_`, `_row_name_` and `_col_name_`

This is definetly coming in version 1. ( Available in[ v1 branch](https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/tree/v1) for testing )

https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/commit/fcf9783a8527f4b169aade17ac37c8ff617f1ef8

**Comment by yesoreyeram** [comment]
Screenshots from version 1

![image](https://user-images.githubusercontent.com/153843/53054631-dd120900-349c-11e9-8d3e-364dd50e5054.png)
![image](https://user-images.githubusercontent.com/153843/53054636-e307ea00-349c-11e9-9069-f59b7f25b885.png)
![image](https://user-images.githubusercontent.com/153843/53054642-e8653480-349c-11e9-9a1a-8a30d87a7e36.png)

**Comment by yesoreyeram** [comment]
This is now merged into master and released as v1.0.0 d14e1e09a03257d0fa9008087da8714368d0d1ff
