### ISSUE TITLE
Number in column header replaced by row name

### ISSUE THREAD

**Issue by lrgapit** [yesoreyeram/yesoreyeram-boomtable-panel#65]
Hey.
I am trying to name three column headers "Phase 1 Current", "Phase 2 Current", "Phase 3 Current" with the same row name. The pattern setup is as follows: 
Pattern = SomePattern
Delimiter = .
Row Name = 2
Col Name = 1
And the "ALIAS BY" fields = "SomePattern.Phase 1 Current.RowName", "SomePattern.Phase 2 Current.RowName", "SomePattern.Phase 3 Current.RowName"

Two of them work well (1 and 3), but where I type in "2" it gets replaced by the row name as such: "Phase RowName Current" instead of "Phase 2 Current"

It might just be that I'm doing something wrong, and if that is the case I hope you can correct me.

BR. Lars

**Comment by yesoreyeram** [comment]
Screenshot of metrics and pattern will be helpful to understand. 

BTW, Have you tried debug mode ?

**Comment by lrgapit** [comment]
Datasource: InfluxDB
Plugin version: 1.0.0
![result](https://user-images.githubusercontent.com/48066485/53519252-2bde2500-3ad3-11e9-9891-68c371b55ce8.png)
![metrics](https://user-images.githubusercontent.com/48066485/53519261-2ed91580-3ad3-11e9-823a-5a04b77c5287.png)
![pattern](https://user-images.githubusercontent.com/48066485/53519270-326c9c80-3ad3-11e9-9028-ae7bbe13cee5.png)
![debug_mode](https://user-images.githubusercontent.com/48066485/53519278-38fb1400-3ad3-11e9-83d3-3b4b1f85ab07.png)

**Comment by yesoreyeram** [comment]
Sorry that you are struggling with the plugins usage.

Works correctly for me.. May be check the pattern rowname, colname. They should be `_2_` and `_1_` respectively.

![image](https://user-images.githubusercontent.com/153843/53594328-8d18fd80-3b92-11e9-9e74-7d8e3d34ac4f.png)
![image](https://user-images.githubusercontent.com/153843/53594342-97d39280-3b92-11e9-9827-734e1840b8d6.png)
![image](https://user-images.githubusercontent.com/153843/53594353-9e620a00-3b92-11e9-85eb-f6902296a6fa.png)

and the panel json looks like

`
{
  "type": "yesoreyeram-boomtable-panel",
  "title": "Panel Title",
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 12,
    "h": 9
  },
  "id": 2,
  "datasource": "Graphite",
  "targets": [
    {
      "target": "alias(carbon.agents.d631700a2142-a.activeConnections, 'SomePattern.Phase 1 Current.RowName')",
      "refId": "A",
      "refCount": 0
    },
    {
      "target": "alias(carbon.agents.d631700a2142-a.avgUpdateTime, 'SomePattern.Phase 2 Current.RowName')",
      "refId": "B",
      "refCount": 0
    },
    {
      "target": "alias(carbon.agents.d631700a2142-a.blacklistMatches, 'SomePattern.Phase 3 Current.RowName')",
      "refId": "C",
      "refCount": 0
    }
  ],
  "activePatternIndex": 0,
  "default_title_for_rows": "Metric",
  "patterns": [
    {
      "row_col_wrapper": "_",
      "bgColors": "green|orange|red",
      "bgColors_overrides": "0->green|2->red|1->yellow",
      "textColors": "red|orange|green",
      "textColors_overrides": "0->red|2->green|1->yellow",
      "clickable_cells_link": "",
      "col_name": "_1_",
      "decimals": 2,
      "delimiter": ".",
      "enable_bgColor": true,
      "enable_bgColor_overrides": false,
      "enable_textColor": false,
      "enable_textColor_overrides": false,
      "enable_clickable_cells": false,
      "enable_time_based_thresholds": false,
      "enable_transform": false,
      "enable_transform_overrides": false,
      "filter": {
        "value_above": "",
        "value_below": ""
      },
      "format": "none",
      "name": "Some Pattern",
      "null_color": "darkred",
      "null_textcolor": "black",
      "null_value": "No data",
      "pattern": "SomePattern",
      "row_name": "_2_",
      "thresholds": "4,5",
      "time_based_thresholds": [],
      "transform_values": "_value_|_value_|_value_",
      "transform_values_overrides": "0->down|1->up",
      "tooltipTemplate": "Series : _series_ <br/>Row Name : _row_name_ <br/>Col Name : _col_name_ <br/>Value : _value_",
      "valueName": "avg"
    }
  ],
  "row_col_wrapper": "_",
  "defaultPattern": {
    "row_col_wrapper": "_",
    "bgColors": "green|orange|red",
    "bgColors_overrides": "0->green|2->red|1->yellow",
    "textColors": "red|orange|green",
    "textColors_overrides": "0->red|2->green|1->yellow",
    "clickable_cells_link": "",
    "col_name": "Value",
    "decimals": 2,
    "delimiter": ".",
    "enable_bgColor": false,
    "enable_bgColor_overrides": false,
    "enable_textColor": false,
    "enable_textColor_overrides": false,
    "enable_clickable_cells": false,
    "enable_time_based_thresholds": false,
    "enable_transform": false,
    "enable_transform_overrides": false,
    "filter": {
      "value_above": "",
      "value_below": ""
    },
    "format": "none",
    "name": "Default Pattern",
    "null_color": "darkred",
    "null_textcolor": "black",
    "null_value": "No data",
    "pattern": "*",
    "row_name": "_series_",
    "thresholds": "70,90",
    "time_based_thresholds": [],
    "transform_values": "_value_|_value_|_value_",
    "transform_values_overrides": "0->down|1->up",
    "tooltipTemplate": "Series : _series_ <br/>Row Name : _row_name_ <br/>Col Name : _col_name_ <br/>Value : _value_",
    "valueName": "avg"
  }
}
`

If this doesn't work, try v1.0 and let me know.  For me works well in v0.5.x and v1.0.0.

**Comment by lrgapit** [comment]
Hey again.
It turned out that  I  looked at the wrong place when checking the version, and after updating to v1.0.0 it works perfectly.

Thanks for great plugin and support, and sorry for wasting your time.

BR. Lars
:)
