### ISSUE TITLE
Heatmap is showing only one row.

### ISSUE THREAD

**Issue by marchiorito** [yesoreyeram/yesoreyeram-boomtable-panel#66]
Hi,

Im using version 0.4.6 on grafana v5.4.2 and using the zabbix datasource
Im trying to create a heatmap like the one on your screenshots.
![image](https://user-images.githubusercontent.com/28105800/53805767-57399780-3f4b-11e9-93b5-d7218ebd6295.png)

As you can see it's displaying only one row. 
It's one host in zabbix with +200 items(metrics) from the nodes it has connected.  each green square is one metric. It's possible to make them fit on multiple lines? or it's possible to disable the scroll bar? .

**Comment by yesoreyeram** [comment]
This is by design. 

In my example, I was referring four different metrics for 200+ servers.  Obviously i use 1server*500 metrcis or 500 servers * 1 metic, I will end up in horizontal or vertical scroll  bar.  

BTW, there is a chance to achieve this, if you group your data with some limited number of groups using alias.


BTW, What is the usecase to show 200 metrics from one host..??

**Comment by marchiorito** [comment]
Thanks for the quick response, i don't know how to group it by alias but im going to investigate it.

i want to have a grid(heatmap) like this to display the status of the 200+ nodes , we need to see if they're connected or disconnected and this is "easy" way to check them all at once.

**Comment by marchiorito** [comment]
the 200+ metrics are 200+ nodes(servers)

**Comment by jstiops** [comment]
i'd love to see some multi row logic as well. Just like the panel repeat configuration perhaps, a "max per row" setting

**Comment by AtebMT** [comment]
I'm clearly missing something obvious, but how do you config the panel to display the heatmap results horizontally? I have a Prometheus query that returns CPU usage. It renders fine as a table. But, no matter what I try, it still displays the results in a table, vertically, one row per server. 

I found [this issue with screenshots](https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/issues/56), but it still didn't help. Must be missing something really obvious here :-( 

I'm using v1.0.0 of the plugin.

**Comment by marchiorito** [comment]
> I'm clearly missing something obvious, but how do you config the panel to display the heatmap results horizontally? I have a Prometheus query that returns CPU usage. It renders fine as a table. But, no matter what I try, it still displays the results in a table, vertically, one row per server.
> 
> I found [this issue with screenshots](https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/issues/56), but it still didn't help. Must be missing something really obvious here :-(
> 
> I'm using v1.0.0 of the plugin.

Invert the col/row , as you can see on my screenshot _0_ and _1_ if i configure _1_ on the row and the other on the col i will display it vertically.

**Comment by AtebMT** [comment]
Yeah, thanks for the prompt reply. Just this morning I got it working.  Digging into the row / column headers in debug mode pointed me in the right direction. 

Thanks.
