### ISSUE TITLE
Getting "No data" even though there's data

### ISSUE THREAD

**Issue by jstiops** [yesoreyeram/yesoreyeram-boomtable-panel#71]
Using Grafana 6.0.1 and Boom Table v1. InfluxDB 1.7.4
I'm getting series from InfluxDB and trying to get a field value with type string into my boom table into a certain column. Pattern matching is going ok for my rows and columns. 
However, I keep getting No Data as value, even though the standard Table panel shows the correct string value.
When i use the query inspector, i can see all my points with the field value being returned.

the value is a string like "MEETING_SLA". 
When i would select another field, with a integer type of value, like IOPs, data immediately shows in. It looks like something specific.

**Comment by yesoreyeram** [comment]
Plugin will handle only numeric values. In case if you need other string segments , use value transform with something like `_1_`
