### ISSUE TITLE
[Enhancements] Missing some font-awesome symbols

### ISSUE THREAD

**Issue by wetterfrosch** [yesoreyeram/yesoreyeram-boomtable-panel#72]
Hi there & thanks for the nice plugin!

I've hesistated a bit to submit this minor issue thus it feels a bit infantile: I am missing some font-awesome icons. Espacally cloud-sun, cloud-sun-rain and solar-panel (from the "free" subset).

Is the plugin like "just a version behind", or is it a more complex issue? Could I help myself?

Thanks for the attention & I am running on boom-table v1.0.0 on Grafana v5.4.3.

**Comment by yesoreyeram** [comment]
This plugin doesn't explictly include any font awesome  icons. But leverage the icons which grafana already provides.  

Currently grafana is using version of 4.7.0 of font awesome. So there is no sun & rain 🌥  which were introducted in FA 5+

https://github.com/grafana/grafana/commits/master/public/sass/base/_font_awesome.scss

**Comment by wetterfrosch** [comment]
Thanks for explaination! I tried to update some file by hand, but with no success (on a deeper view; who, it really seems more complex than just replacing some font-files). So I opened [a kind request on this at Grafana's place](https://github.com/grafana/grafana/issues/16074).

**Comment by yesoreyeram** [comment]
Closing this issue as this is not something that this plugin can fix.  Leaving it to grafana.
