### ISSUE TITLE
[Feature Request] Multiple values in single query

### ISSUE THREAD

**Issue by yellowpattern** [yesoreyeram/yesoreyeram-boomtable-panel#77]
This query is incompatible with Boomtable:

SELECT non_negative_difference("read") AS "read", non_negative_difference("write") AS "write" FROM "disk" WHERE ("type" = 'disk_ops' A AND time >= now() - 5m GROUP BY "host",time(1m)"

The workaround is to use a single query for each column.

**Comment by yesoreyeram** [comment]
Yes. Boomtable doesn't support multiple values in single query. I can't implement this anytime soon as this require huge effort and design changes.

**Comment by florianwgnr** [comment]
I think this has been fixed, because multiple values in one query works for me:

SELECT last("uptime") AS "last.m1.uptime", last("test") AS "last.m1.test" FROM "machines" WHERE ("id" = 'm1') AND time >= now() - 6h GROUP BY time(1m)

**Comment by yesoreyeram** [comment]
Glad to hear that you sorted out.

**Comment by balakrishnabk** [comment]
> SELECT last("uptime") AS "last.m1.uptime", last("test") AS "last.m1.test" FROM "machines" WHERE ("id" = 'm1') AND time >= now() - 6h GROUP BY time(1m)

@florianwgnr  : I am curious to know how the dashboard looks with multiple values. care to share the dashboard screenshot ?
Regards,
Bala.

**Comment by florianwgnr** [comment]
One select statement like this: 
`SELECT last("Demo 1") AS "[[templateVar]].Demo1", last("Demo 2") AS "[[templateVar]].Demo2", ...`

and this is repeated for the template variables. Looks like this:

![grafik](https://user-images.githubusercontent.com/39341393/61769612-1ef80000-adeb-11e9-87d3-e325def24717.png)
