### ISSUE TITLE
[Feature] Support the use of _2_, _3_, etc, in URL links

### ISSUE THREAD

**Issue by yellowpattern** [yesoreyeram/yesoreyeram-boomtable-panel#78]
When composing URLs to be attributed to a value, the only options for referencing column and row names are _row_name_ and _col_name_. The result is that if the column name is a product of adding extra text then _col_name_ potentially is no longer useful for the URL.

For example, I might have two columns titled "sda", one for disk space and one for IOPS. What I would like to do is have the columns "DF sda" and "IOPS sda" and then use "sda" to pass as a variable to the respective web pages for each.

**Comment by balakrishnabk** [comment]
even I am looking for a similar option where the URL is dynamically created using non row/column names.

**Comment by balakrishnabk** [comment]
I did a workaround by using "Overrides/Value transform Overrides" and the cell value shows as required.  So, if there is an option to render the value as URL, then that also solves my problem. snapshot attached

**Comment by yesoreyeram** [comment]
Done. Available in master branch with the commit 709b72da383543b4c24e9a524196339ecf438896

You can use links something like

`https://google.com/?servername=_2_&environment=_0_&metric=_3_&value=_value_`

**WARNING** : Be aware that, if your URL have something like, `http://some_2_domain.com/?q=_2_` , then the URL will break. In that case, You may need to change the row_col_wrapper in the options

**Comment by balakrishnabk** [comment]
Thanks a lot !

**Comment by balakrishnabk** [comment]
any chance of cutting the release with this new feature in near-future OR how to download/test this

**Comment by yesoreyeram** [comment]
https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/archive/master.zip

**Comment by balakrishnabk** [comment]
Thank you, works as expected in our test environment.  will wait for productive release.
