### ISSUE TITLE
[Query] empty tag shown on boomtable

### ISSUE THREAD

**Issue by redmuchroom** [yesoreyeram/yesoreyeram-boomtable-panel#79]
Dear, 

we are currently trying to setup a boomtable based on an influxdb. 
the first row shown on the table is in fact an unexisting value (tag is empty). see pic below.
I checked the influx table : all data are present with the flag. 

I'm maybe wrong the regex part on the pattern selection...? 

thanks for your help!

![image](https://user-images.githubusercontent.com/50101611/56887866-f756fd00-6a72-11e9-87b2-6da036a1c895.png)
![image](https://user-images.githubusercontent.com/50101611/56887923-18b7e900-6a73-11e9-8b15-a72e17c3aee4.png)

**Comment by yesoreyeram** [comment]
you mean, you are not expecting that empty row??

Could you inspect query output using `Query Inspector` option in metics if the original query returns expected values? My wild guess is that your query returns some data without that tag value.

**Comment by redmuchroom** [comment]
thanks for your quick reply. 
Indeed... the query returns the data without that tag...strange...
but definitely on my side ;)

thanks a lot!

**Comment by yesoreyeram** [comment]
Thanks. Feel free to close if no more assistance required.

**Comment by redmuchroom** [comment]
thanks!
