### ISSUE TITLE
Support to Zabbix data source

### ISSUE THREAD

**Issue by ceinmart** [yesoreyeram/yesoreyeram-boomtable-panel#80]
Hi, 

It's do not support Zabbix data source ? 
I even unable to test it ? 
Because the panel do not appear as option when I tried to add it to my dashboard. 

I never used this panel, but considering the screen shots, looks very promising to work with Zabbix.

Regards

**Comment by yesoreyeram** [comment]
Hi -  I am not sure how zabbix works.  I dont have any experiece with that..

This plugin works with any datasource that returns timeseries format data

**Comment by brycefisher** [comment]
@ceinmart I had a similar issue when trying to use Azure Data Explorer on a free Grafana cloud instance. I kept trying to create new panels from scratch, picking visualization before writing a query, and eventually the BoomTable appeared. I logged in again to Grafana.com _and_ I refreshed the Settings > Plugins page several times too.

When I spun up a fresh docker container using the stock grafana image and installing BoomTable, that worked fine for me:

```
docker run \
   -d \
   -p 3000:3000 \
   --name=grafana \
   -e "GF_INSTALL_PLUGINS=yesoreyeram-boomtable-panel" \
    grafana/grafana
```

(See docs on this: https://grafana.com/docs/guides/getting_started/ and https://grafana.com/docs/installation/docker/#installing-plugins-for-grafana).

So, I suspect this is a problem of inconsistent state somewhere inside of Grafana (or possibly some delayed processing on a Grafana Cloud).

**Comment by insanemor** [comment]
I'm testing with zabbix ...

but it doesn't work perfectly, it can't group servers

![image](https://user-images.githubusercontent.com/22816853/67777461-86ec6100-fa40-11e9-862f-1c24de565cf4.png)

**Comment by insanemor** [comment]
Validated here, managed to run with zabbix

you can add that works

**Comment by yesoreyeram** [comment]
Hi @insanemor - if you could share your query config with some screenshots that will be useful to others.

**Comment by insanemor** [comment]
Yes, follow the settings and I used


In metric I used one for each tracked item collection in zabbix

![image](https://user-images.githubusercontent.com/22816853/67853821-100da180-faee-11e9-8407-7f9f513c6198.png)


In patterns I created one for each item with its regex, using the delimiter:

![image](https://user-images.githubusercontent.com/22816853/67854032-624ec280-faee-11e9-9ddc-00a52698f796.png)

Final result

![image](https://user-images.githubusercontent.com/22816853/67854268-c70a1d00-faee-11e9-9dfc-4013b94e47e1.png)


The only thing I couldn't do was sort the names of the monitored servers in alphabetical order.

**Comment by yesoreyeram** [comment]
Brillinat @insanemor . Thank you

**Comment by yesoreyeram** [comment]
If u r using master branch, u may notice that they are Already sorted.
