### ISSUE TITLE
Default pattern 

### ISSUE THREAD

**Issue by b4dboi** [yesoreyeram/yesoreyeram-boomtable-panel#81]
Hi, thank you for the plugin. I am playing with it now, but I am unable to get rid of the default pattern. Even if I add a new valid patterns I am unable to disable the default one, that adds additional row(s). Did I overlook something in the documentation?

**Comment by yesoreyeram** [comment]
You can't remove the default pattern. That's the expected behaviour. Why do you need to remove the default pattern?

**Comment by b4dboi** [comment]
Maybe I misunderstood the concept. I have several series from InfluxDB, where each of them is separately served by some custom pattern forming demanded rows and columns. However, the default pattern with its asterisk notation adds the series data to the table, what I am not able to suppress. If I delete Row Name and Col Name at the default pattern, I end up with a single cell containing **Duplicate matches** caused by the conflicting custom and default patterns. The custom patterns work well. Is there some flaw in my approach?

**Comment by yesoreyeram** [comment]
All the series from influx should match against any pattern and also should yield unique set of row and col name. Try enabling debug mode.

**Comment by b4dboi** [comment]
I am still missing the idea why the default pattern is required. For example, look at the screenshot below. I have two influx series (separated by '-' char). There are two patterns defined for a subset of results I want to shown in the table (patterns **Locks** and **DBcount** underlined red in the debug window), that works well as you can see from the resultant table (the second row underlined red as well). 

However, the default pattern matches data again and adds all series to the resultant table, which is not required in my case. Is there a way to suppress such behavior?

![table](https://user-images.githubusercontent.com/11676900/58251470-02483900-7d64-11e9-8b87-238f32cad770.png)

**Comment by yesoreyeram** [comment]
How do you want to deal the series other than Locks and Db Count? That's where the default pattern comes into picture.  if you want ot discard them from the display, change the query to return only Locks nad DB count.

**Comment by b4dboi** [comment]
Great, I got it. I knew I somehow missed the point, as I expected filtering at the plugin level not at data source. Thank you
