### ISSUE TITLE
light theme : font remains white

### ISSUE THREAD

**Issue by redmuchroom** [yesoreyeram/yesoreyeram-boomtable-panel#82]
Dear,

I'm trying to use the boom panel with the light theme. It seems that the font remains white...
do you have any advice to correct it?

thanks,

br
![image](https://user-images.githubusercontent.com/50101611/58312950-bdc4a800-7e0c-11e9-88cf-248ab294d58f.png)

**Comment by yesoreyeram** [comment]
I am not able to reproduce this.  What version of plugin and grafana ?

**Comment by yesoreyeram** [comment]
![image](https://user-images.githubusercontent.com/153843/58317080-f8c6db80-7e0c-11e9-90f5-5a6afabcd492.png)

**Comment by redmuchroom** [comment]
hi thanks,
grafana: 6.1.6
plugin : 1.0.0

**Comment by yesoreyeram** [comment]
I couldn't reproduce this yet.  If you don't mind, post the panel json without sensitive information? 

I just tested in brand new installtion with the above versions.

![image](https://user-images.githubusercontent.com/153843/58318557-e7cb9980-7e0f-11e9-8b76-c157451fb7ae.png)

**Comment by redmuchroom** [comment]
here it is: 
{
  "activePatternIndex": 8,
  "datasource": "pilot4",
  "debug_mode": false,
  "defaultPattern": {
    "bgColors": "green|orange|red",
    "bgColors_overrides": "0->green|2->red|1->yellow",
    "clickable_cells_link": "",
    "col_name": "",
    "decimals": "",
    "delimiter": ".",
    "enable_bgColor": false,
    "enable_bgColor_overrides": false,
    "enable_clickable_cells": false,
    "enable_textColor": false,
    "enable_textColor_overrides": false,
    "enable_time_based_thresholds": false,
    "enable_transform": false,
    "enable_transform_overrides": false,
    "filter": {
      "value_above": "",
      "value_below": ""
    },
    "format": "none",
    "name": "Default Pattern",
    "null_color": "darkred",
    "null_textcolor": "black",
    "null_value": "No data",
    "pattern": "*",
    "row_col_wrapper": "_",
    "row_name": "",
    "textColors": "red|orange|green",
    "textColors_overrides": "0->red|2->green|1->yellow",
    "thresholds": "0",
    "time_based_thresholds": [],
    "tooltipTemplate": "Series : _series_ <br/>Row Name : _row_name_ <br/>Col Name : _col_name_ <br/>Value : _value_",
    "transform_values": "_value_|_value_|_value_",
    "transform_values_overrides": "0->down|1->up",
    "valueName": "total"
  },
  "default_title_for_rows": "Batteries",
  "gridPos": {
    "h": 8,
    "w": 11,
    "x": 0,
    "y": 6
  },
  "hideTimeOverride": false,
  "hide_first_column": true,
  "hide_headers": false,
  "id": 5,
  "links": [],
  "maxPerRow": 6,
  "patterns": [
    {
      "bgColors": "green|orange|red",
      "bgColors_overrides": "0->green|2->red|1->yellow",
      "clickable_cells_link": "",
      "col_name": "_1_",
      "decimals": "0",
      "delimiter": ".",
      "enable_bgColor": false,
      "enable_bgColor_overrides": false,
      "enable_clickable_cells": true,
      "enable_textColor": false,
      "enable_textColor_overrides": false,
      "enable_time_based_thresholds": false,
      "enable_transform": false,
      "enable_transform_overrides": false,
      "filter": {
        "value_above": "",
        "value_below": ""
      },
      "format": "none",
      "name": "Identificator",
      "null_color": "darkred",
      "null_textcolor": "black",
      "null_value": "No data",
      "pattern": "Var1.*$",
      "row_col_wrapper": "_",
      "row_name": "_2_",
      "textColors": "red|orange|green",
      "textColors_overrides": "0->red|2->green|1->yellow",
      "thresholds": "0,1",
      "time_based_thresholds": [],
      "tooltipTemplate": "Series : _series_ <br/>Row Name : _row_name_ <br/>Col Name : _col_name_ <br/>Value : _value_",
      "transform_values": "_fa-battery-empty,red_ |_fa-battery-quarter,yellow_ |_fa-battery-full,green_",
      "transform_values_overrides": "0->down|1->up",
      "valueName": "current"
    },
    {
      "bgColors": "green|orange|red",
      "bgColors_overrides": "0->green|2->red|1->yellow",
      "clickable_cells_link": "",
      "col_name": "_1_",
      "decimals": 2,
      "delimiter": ".",
      "enable_bgColor": false,
      "enable_bgColor_overrides": false,
      "enable_clickable_cells": false,
      "enable_textColor": false,
      "enable_textColor_overrides": false,
      "enable_time_based_thresholds": false,
      "enable_transform": true,
      "enable_transform_overrides": false,
      "filter": {
        "value_above": "",
        "value_below": ""
      },
      "format": "none",
      "name": "Communication",
      "null_color": "darkred",
      "null_textcolor": "black",
      "null_value": "No data",
      "pattern": "Var2.*$",
      "row_col_wrapper": "_",
      "row_name": "_2_",
      "textColors": "red|orange|green",
      "textColors_overrides": "0->red|2->green|1->yellow",
      "thresholds": "0,1",
      "time_based_thresholds": [],
      "tooltipTemplate": "Series : _series_ <br/>Row Name : _row_name_ <br/>Col Name : _col_name_ <br/>Value : _value_",
      "transform_values": "|_fa-battery-quarter,red_ |_fa-battery-full,green_",
      "transform_values_overrides": "0->down|1->up",
      "valueName": "current"
    },
    {
      "bgColors": "green|orange|red",
      "bgColors_overrides": "0->green|2->red|1->yellow",
      "clickable_cells_link": "",
      "col_name": "_1_",
      "decimals": 2,
      "delimiter": ".",
      "enable_bgColor": false,
      "enable_bgColor_overrides": false,
      "enable_clickable_cells": false,
      "enable_textColor": false,
      "enable_textColor_overrides": false,
      "enable_time_based_thresholds": false,
      "enable_transform": false,
      "enable_transform_overrides": false,
      "filter": {
        "value_above": "",
        "value_below": ""
      },
      "format": "volt",
      "name": "Voltage",
      "null_color": "darkred",
      "null_textcolor": "black",
      "null_value": "No data",
      "pattern": "Var3.*$",
      "row_col_wrapper": "_",
      "row_name": "_2_",
      "textColors": "red|orange|green",
      "textColors_overrides": "0->red|2->green|1->yellow",
      "thresholds": "70,90",
      "time_based_thresholds": [],
      "tooltipTemplate": "Series : _series_ <br/>Row Name : _row_name_ <br/>Col Name : _col_name_ <br/>Value : _value_",
      "transform_values": "_value_|_value_|_value_",
      "transform_values_overrides": "0->down|1->up",
      "valueName": "current"
    },
    {
      "bgColors": "green|orange|red",
      "bgColors_overrides": "0->green|2->red|1->yellow",
      "clickable_cells_link": "",
      "col_name": "_1_",
      "decimals": 2,
      "delimiter": ".",
      "enable_bgColor": false,
      "enable_bgColor_overrides": false,
      "enable_clickable_cells": false,
      "enable_textColor": false,
      "enable_textColor_overrides": false,
      "enable_time_based_thresholds": false,
      "enable_transform": false,
      "enable_transform_overrides": false,
      "filter": {
        "value_above": "",
        "value_below": ""
      },
      "format": "locale",
      "name": "Resistance",
      "null_color": "darkred",
      "null_textcolor": "black",
      "null_value": "No data",
      "pattern": "Var4.*$",
      "row_col_wrapper": "_",
      "row_name": "_2_",
      "textColors": "red|orange|green",
      "textColors_overrides": "0->red|2->green|1->yellow",
      "thresholds": "70,90",
      "time_based_thresholds": [],
      "tooltipTemplate": "",
      "transform_values": "_value_|_value_|_value_",
      "transform_values_overrides": "0->down|1->up",
      "valueName": "current"
    },
    {
      "bgColors": "green|orange|red",
      "bgColors_overrides": "0->green|2->red|1->yellow",
      "clickable_cells_link": "",
      "col_name": "_1_",
      "decimals": "1",
      "delimiter": ".",
      "enable_bgColor": false,
      "enable_bgColor_overrides": false,
      "enable_clickable_cells": false,
      "enable_textColor": false,
      "enable_textColor_overrides": false,
      "enable_time_based_thresholds": false,
      "enable_transform": false,
      "enable_transform_overrides": false,
      "filter": {
        "value_above": "",
        "value_below": ""
      },
      "format": "celsius",
      "name": "Temperature",
      "null_color": "darkred",
      "null_textcolor": "black",
      "null_value": "No data",
      "pattern": "Var5.*$",
      "row_col_wrapper": "_",
      "row_name": "_2_",
      "textColors": "red|orange|green",
      "textColors_overrides": "0->red|2->green|1->yellow",
      "thresholds": "70,90",
      "time_based_thresholds": [],
      "tooltipTemplate": "Series : _series_ <br/>Row Name : _row_name_ <br/>Col Name : _col_name_ <br/>Value : _value_",
      "transform_values": "_value_|_value_|_value_",
      "transform_values_overrides": "0->down|1->up",
      "valueName": "current"
    },
    {
      "bgColors": "green|orange|red",
      "bgColors_overrides": "0->green|2->red|1->yellow",
      "clickable_cells_link": "",
      "col_name": "_1_",
      "decimals": 2,
      "delimiter": ".",
      "enable_bgColor": false,
      "enable_bgColor_overrides": false,
      "enable_clickable_cells": false,
      "enable_textColor": false,
      "enable_textColor_overrides": false,
      "enable_time_based_thresholds": false,
      "enable_transform": false,
      "enable_transform_overrides": false,
      "filter": {
        "value_above": "",
        "value_below": ""
      },
      "format": "none",
      "name": "SOC",
      "null_color": "darkred",
      "null_textcolor": "black",
      "null_value": "No data",
      "pattern": "Var6.*$",
      "row_col_wrapper": "_",
      "row_name": "_2_",
      "textColors": "red|orange|green",
      "textColors_overrides": "0->red|2->green|1->yellow",
      "thresholds": "70,90",
      "time_based_thresholds": [],
      "tooltipTemplate": "Series : _series_ <br/>Row Name : _row_name_ <br/>Col Name : _col_name_ <br/>Value : _value_",
      "transform_values": "_value_|_value_|_value_",
      "transform_values_overrides": "0->down|1->up",
      "valueName": "avg"
    },
    {
      "bgColors": "green|orange|red",
      "bgColors_overrides": "0->green|2->red|1->yellow",
      "clickable_cells_link": "",
      "col_name": "_1_",
      "decimals": 2,
      "delimiter": ".",
      "enable_bgColor": false,
      "enable_bgColor_overrides": false,
      "enable_clickable_cells": false,
      "enable_textColor": false,
      "enable_textColor_overrides": false,
      "enable_time_based_thresholds": false,
      "enable_transform": false,
      "enable_transform_overrides": false,
      "filter": {
        "value_above": "",
        "value_below": ""
      },
      "format": "none",
      "name": "SOH",
      "null_color": "darkred",
      "null_textcolor": "black",
      "null_value": "No data",
      "pattern": "Var7.*$",
      "row_col_wrapper": "_",
      "row_name": "_2_",
      "textColors": "red|orange|green",
      "textColors_overrides": "0->red|2->green|1->yellow",
      "thresholds": "70,90",
      "time_based_thresholds": [],
      "tooltipTemplate": "Series : _series_ <br/>Row Name : _row_name_ <br/>Col Name : _col_name_ <br/>Value : _value_",
      "transform_values": "_value_|_value_|_value_",
      "transform_values_overrides": "0->down|1->up",
      "valueName": "avg"
    },
    {
      "bgColors": "green|orange|red",
      "bgColors_overrides": "0->green|2->red|1->yellow",
      "clickable_cells_link": "",
      "col_name": "_1_",
      "decimals": 2,
      "delimiter": ".",
      "enable_bgColor": false,
      "enable_bgColor_overrides": false,
      "enable_clickable_cells": false,
      "enable_textColor": false,
      "enable_textColor_overrides": false,
      "enable_time_based_thresholds": false,
      "enable_transform": false,
      "enable_transform_overrides": false,
      "filter": {
        "value_above": "",
        "value_below": ""
      },
      "format": "none",
      "name": "Alarms",
      "null_color": "darkred",
      "null_textcolor": "black",
      "null_value": "No data",
      "pattern": "Var8.*$",
      "row_col_wrapper": "_",
      "row_name": "_2_",
      "textColors": "red|orange|green",
      "textColors_overrides": "0->red|2->green|1->yellow",
      "thresholds": "70,90",
      "time_based_thresholds": [],
      "tooltipTemplate": "Series : _series_ <br/>Row Name : _row_name_ <br/>Col Name : _col_name_ <br/>Value : _value_",
      "transform_values": "_value_|_value_|_value_",
      "transform_values_overrides": "0->down|1->up",
      "valueName": "avg"
    },
    {
      "bgColors": "green|orange|red",
      "bgColors_overrides": "0->green|2->red|1->yellow",
      "clickable_cells_link": "",
      "col_name": "_1_",
      "decimals": 2,
      "delimiter": ".",
      "enable_bgColor": false,
      "enable_bgColor_overrides": false,
      "enable_clickable_cells": false,
      "enable_textColor": false,
      "enable_textColor_overrides": false,
      "enable_time_based_thresholds": false,
      "enable_transform": false,
      "enable_transform_overrides": false,
      "filter": {
        "value_above": "",
        "value_below": ""
      },
      "format": "none",
      "name": "Boltzmann",
      "null_color": "darkred",
      "null_textcolor": "black",
      "null_value": "No data",
      "pattern": "Var9.*$",
      "row_col_wrapper": "_",
      "row_name": "_2_",
      "textColors": "red|orange|green",
      "textColors_overrides": "0->red|2->green|1->yellow",
      "thresholds": "70,90",
      "time_based_thresholds": [],
      "tooltipTemplate": "Series : _series_ <br/>Row Name : _row_name_ <br/>Col Name : _col_name_ <br/>Value : _value_",
      "transform_values": "_value_|_value_|_value_",
      "transform_values_overrides": "0->down|1->up",
      "valueName": "avg"
    }
  ],
  "repeatDirection": "v",
  "row_col_wrapper": "_",
  "targets": [
    {
      "alias": "Var1.Battery.$tag_Battery_Number",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "Battery_Number"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "Battery_Identification",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT last(\"value\") FROM \"Temperature\" WHERE $timeFilter GROUP BY time($__interval), \"battery_number\" fill(null)",
      "rawQuery": false,
      "refId": "G",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "last"
          }
        ]
      ],
      "tags": [
        {
          "key": "Host",
          "operator": "=",
          "value": "011900001"
        }
      ]
    },
    {
      "alias": "Var2.Status.$tag_Battery_Number",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "Battery_Number"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "Battery_Status_Of_Communication",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT last(\"value\") FROM \"Temperature\" WHERE $timeFilter GROUP BY time($__interval), \"battery_number\" fill(null)",
      "rawQuery": false,
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "last"
          }
        ]
      ],
      "tags": [
        {
          "key": "Host",
          "operator": "=",
          "value": ""
        }
      ]
    },
    {
      "alias": "Var3.Voltage.$tag_Battery_Number",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "Battery_Number"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "Battery_Voltage",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT last(\"value\") / 1000 \nFROM \"Battery_Voltage\" WHERE $timeFilter GROUP BY time($__interval), \"Battery_Number\" fill(null)",
      "rawQuery": true,
      "refId": "B",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "last"
          }
        ]
      ],
      "tags": []
    },
    {
      "alias": "Var4.Resistance.$tag_Battery_Number",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "Battery_Number"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "Battery_Internal_Resistance",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT last(\"value\") FROM \"Battery_Internal_Resistance\" WHERE $timeFilter GROUP BY time($__interval), \"Battery_Number\" fill(null)",
      "rawQuery": false,
      "refId": "C",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "last"
          }
        ]
      ],
      "tags": [
        {
          "key": "Host",
          "operator": "=",
          "value": ""
        }
      ]
    },
    {
      "alias": "Var5.Temperature.$tag_Battery_Number",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "Battery_Number"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "Battery_Temperature",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT last(\"value\")/10 FROM \"Battery_Temperature\" WHERE $timeFilter GROUP BY time($__interval), \"Battery_Number\" fill(null)",
      "rawQuery": true,
      "refId": "D",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "last"
          }
        ]
      ],
      "tags": []
    },
    {
      "alias": "Var6.SOC.$tag_Battery_Number",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "Battery_Number"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "Battery_SOC",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT last(\"value\") FROM \"Temperature\" WHERE $timeFilter GROUP BY time($__interval), \"battery_number\" fill(null)",
      "rawQuery": false,
      "refId": "E",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "last"
          }
        ]
      ],
      "tags": [
        {
          "key": "Host",
          "operator": "=",
          "value": ""
        }
      ]
    },
    {
      "alias": "Var7.SOH.$tag_Battery_Number",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "Battery_Number"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "Battery_SOH",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT last(\"value\") FROM \"Temperature\" WHERE $timeFilter GROUP BY time($__interval), \"battery_number\" fill(null)",
      "rawQuery": false,
      "refId": "F",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "last"
          }
        ]
      ],
      "tags": [
        {
          "key": "Host",
          "operator": "=",
          "value": ""
        }
      ]
    },
    {
      "alias": "Var8.Alarms.$tag_Battery_Number",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "Battery_Number"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "Battery_Alarms",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT last(\"value\") FROM \"Temperature\" WHERE $timeFilter GROUP BY time($__interval), \"battery_number\" fill(null)",
      "rawQuery": false,
      "refId": "H",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "last"
          }
        ]
      ],
      "tags": [
        {
          "key": "Host",
          "operator": "=",
          "value": ""
        }
      ]
    },
    {
      "alias": "Var9..$tag_Battery_Number",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "Battery_Number"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "Battery_Alarms",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT last(\"value\") FROM \"Temperature\" WHERE $timeFilter GROUP BY time($__interval), \"battery_number\" fill(null)",
      "rawQuery": false,
      "refId": "I",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "last"
          }
        ]
      ],
      "tags": [
        {
          "key": "Host",
          "operator": "=",
          "value": ""
        }
      ]
    }
  ],
  "text_alignment_firstcolumn": "CENTER",
  "text_alignment_header": "CENTER",
  "text_alignment_values": "CENTER",
  "title": "Real-time Data of Batteries",
  "type": "yesoreyeram-boomtable-panel"
}

**Comment by redmuchroom** [comment]
hi ,
by any chance did you manage to reproduce the issue?
if you need any help from me, feel free :)

thanks

**Comment by yesoreyeram** [comment]
Sorry i couldn't reproduce this. Any help appreciated. Feel free to raise PR if you know the root cause.

**Comment by redmuchroom** [comment]
hi,

I just put the debug mode... and indeed it is confirmed that the text color is white :) .
Do I miss something in the configuration? I think more and more that it is a misused from my side again...

![image](https://user-images.githubusercontent.com/50101611/59027755-2a529480-885a-11e9-8c02-a05e2020bcc8.png)

thanks

**Comment by yesoreyeram** [comment]
Got it..  There is a piece of code which always return white color irrespecitive of theme.  

https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/blob/master/src/app/boom/BoomSeries.ts#L126

Fix coming soon.

**Comment by yesoreyeram** [comment]
@redmuchroom Fix available in latest master branch
