### ISSUE TITLE
[Help Required] Links to dashboard

### ISSUE THREAD

**Issue by Bounzz** [yesoreyeram/yesoreyeram-boomtable-panel#85]
Hi,

**What you are struggling with**

When i activate Table Cell link, i just have one link for all cell.

**What you tried**

I tried to have a link per rows

This is possible ?

**Related Issues and Links**

![capture](https://user-images.githubusercontent.com/21198622/59593604-86d37080-90f2-11e9-82a0-0393787c5b66.png)

Thanks

**Comment by yesoreyeram** [comment]
Links can't be set to first column/row. links support only for other table cells which represents some value.

**Comment by aerokite** [comment]
How can I send variable values with a link from the cell?

**Comment by yesoreyeram** [comment]
@aerokite template variables in links are yet supported.  Related issue #57

**Comment by balakrishnabk** [comment]
Hi,
Sorry for commenting on the closed issue.  Can the same (url linking) be applied to 1st row.
I want my 1st row/header to be hyperlink able.

Thanks for the wonderful plugin and support.

Regards,
Bala.
