### ISSUE TITLE
[Feature Request] Support for 'Time of last point' stat similar to singlestat panel.

### ISSUE THREAD

**Issue by digrich** [yesoreyeram/yesoreyeram-boomtable-panel#86]
**Is your feature request related to a problem? Please describe.**
In one of our use case, we want to show the time of last data point.

**Describe the solution you'd like**
Support of "Time of last point" stat similar to singlestat panel. This helps us to display the time of last data point.

**Describe alternatives you've considered**
I could not figure any alternative to show the time of last data point in boomtable. 

**Additional context**

**Comment by yesoreyeram** [comment]
Nothing significant. Only thing you need to is `Alias` in your metrics in some delimited form. something like this ( using dot delimiter here. Use whichever appropriate to you )

![image](https://user-images.githubusercontent.com/153843/59835362-68af7f80-9341-11e9-87ac-383ea2c134a1.png)

**Comment by yesoreyeram** [comment]
Nothing significant. Only thing you need to is `Alias` in your metrics in some delimited form. something like this ( using dot delimiter here. Use whichever appropriate to you )

![image](https://user-images.githubusercontent.com/153843/59835362-68af7f80-9341-11e9-87ac-383ea2c134a1.png)

**Comment by digrich** [comment]
Hi @yesoreyeram - Will you be having any tentative timeline, when this feature would be supported?

**Comment by yesoreyeram** [comment]
Hi @digrich , i don't have any timeline for this. But PRs are welcome.
