### ISSUE TITLE
[Feature Request] Cloudwatch setup instructions

### ISSUE THREAD

**Issue by tomisaacson** [yesoreyeram/yesoreyeram-boomtable-panel#87]
**Describe the solution you'd like**
Cloudwatch instructions, similar to those for Prometheus, InfluxDB and Azure.

**Comment by yesoreyeram** [comment]
Nothing significant. Only thing you need to is `Alias` in your metrics in some delimited form. something like this ( using dot delimiter here. Use whichever appropriate to you )

![image](https://user-images.githubusercontent.com/153843/59835362-68af7f80-9341-11e9-87ac-383ea2c134a1.png)

**Comment by tomisaacson** [comment]
But how can I set it up to display a table of data? If I do this I only get a single row:
![boom](https://user-images.githubusercontent.com/11143432/59969647-df00eb80-95a6-11e9-90c0-71502c8cc1dd.png)
What I want is each EC2 instance displayed on a separate row.

**Comment by yesoreyeram** [comment]
You may need to propely `alias` your results. in your case, alias should return the instance name or id.

**Comment by tomisaacson** [comment]
It's not the `alias` that's the problem, it's the fact that I'm only getting a single result.
