### ISSUE TITLE
[Bug] Scroll doesn't work after 1st load

### ISSUE THREAD

**Issue by aerokite** [yesoreyeram/yesoreyeram-boomtable-panel#88]
When a dashboard is loaded the first time, scroll doesn't work. It works if I resize the table or select to view/edit the table.

 - Grafana version: Grafana v6.2.4 (ee01897)
 - Plugin version: 1.1.0-unreleased

**Comment by balakrishnabk** [comment]
Thanks for opening this bug, even I have the same issue.  my versions below.  This was working fine with grafana V5.x
grafana =Grafana v6.2.2 (07540df)
boomtable = 1.1.0-unreleased

**Comment by RhynoMeyer** [comment]
Can confirm this bug for me as well: Using versions:
- Grafana v6.2.1
- Boom Table 1.0.0
