### ISSUE TITLE
[Feature Request] Option to include global time range in the cell links

### ISSUE THREAD

**Issue by aparnaannapragada** [yesoreyeram/yesoreyeram-boomtable-panel#89]
**Is your feature request related to a problem? Please describe.**
The table will be displaying data for a certain period of time and if i click on the cell for drilldown, it routes to another dashboard with different time range.

**Describe the solution you'd like**

Probably an option to 'include time range' as shown below (taken from grafana 'Table' Panel) will help.

![image](https://user-images.githubusercontent.com/30102958/60509227-0ca60d00-9cea-11e9-8d86-a22590583602.png)

**Describe alternatives you've considered**
No alternatives crossed my mind. Please let me know if i could try something to achieve this.

**Comment by yesoreyeram** [comment]
Now you will have two more options

![image](https://user-images.githubusercontent.com/153843/60989647-6e93f180-a33e-11e9-95fe-0277e214a2ce.png)

**Comment by aparnaannapragada** [comment]
That's awesome ... Thank you!
