### ISSUE TITLE
[Feature Request] Dynamic panel height

### ISSUE THREAD

**Issue by aerokite** [yesoreyeram/yesoreyeram-boomtable-panel#91]
In my table panel, I have 1 to 10 rows. I do not want to use the scroll nor pagination. So if I set panel height for 10 rows, most of the time, the panel has only 1/2 rows (dynamic). It looks odd then.

I would like to have this panel to dynamically resize its height base on the row count.

<img width="1354" alt="Screenshot 2019-07-11 at 1 07 03 AM" src="https://user-images.githubusercontent.com/4655476/60997305-4c1eca00-a378-11e9-90f7-d721cdf2cd19.png">

**Comment by yesoreyeram** [comment]
If this panel dynamically resize, then the adjacent panel's positions will keep changing which is not ideal.

Does any other panel does dynamic resize?

**Comment by aerokite** [comment]
I haven't seen any. But this feature can be optional. If anyone wants to use it.

**Comment by yesoreyeram** [comment]
Panels don't handle the height of themself. They are controlled by grafana / dashboard.  When creating the panel, user will define its height. Modifying the height of self will affect the position of the other panels in the dashboard.

Closing this as this not a valid usecase for plugin.  Let me know if you have any other thougts.
