### ISSUE TITLE
[Bug] Template Variables in cells URL - problem with "All"

### ISSUE THREAD

**Issue by florianwgnr** [yesoreyeram/yesoreyeram-boomtable-panel#92]
**Describe the bug**
When using template variables in a cells URL and the template variable is set to "All", every panel has the variable "all" in it.

e.g.: You can choose between line 1, line 2 or all lines -> When choosing "all", two panels appear, first panel is line 1, second panel is line 2 (that works fine). When using the cells target URL with the variable [[Line]], "All" is not replaced by "1" or "2".

**Screenshots**

Template Variable
![grafik](https://user-images.githubusercontent.com/39341393/61025614-95d7d680-a3b1-11e9-9a6a-88575da43765.png)

Link for every row
![grafik](https://user-images.githubusercontent.com/39341393/61025740-dcc5cc00-a3b1-11e9-996e-59fd221dc117.png)

**Version Details:**
 - Grafana version : 6.2.5
 - Plugin version : downloaded master

**Comment by yesoreyeram** [comment]
Hi @florianwgnr  - Fix is now available in master. Feel free to test and let me know how this goes

**Comment by florianwgnr** [comment]
@yesoreyeram Thank you for your help - the fix works great now!
