### ISSUE TITLE
[non-technical] Official plugin still shows 1.0.0

### ISSUE THREAD

**Issue by balakrishnabk** [yesoreyeram/yesoreyeram-boomtable-panel#95]
Hi,
thanks for the new 1.2.0 release version, but the official pages still show 1.0.0.  Is there some process wait time till the repo shows the latest release version.
I want to move from master/latest to release version in my production.
https://grafana.com/grafana/plugins/yesoreyeram-boomtable-panel/changelog
Regards,
Bala

**Comment by yesoreyeram** [comment]
Hi @balakrishnabk - There is a pull request waiting with grafana team to approve.   You can follow the status there.

https://github.com/grafana/grafana-plugin-repository/pull/451
