### ISSUE TITLE
[Help Required] Need help hiding series

### ISSUE THREAD

**Issue by dixiesk** [yesoreyeram/yesoreyeram-boomtable-panel#99]
**What you are struggling with**

Series having a value below the configured 'hide series' are still being shown

**What you tried**

- changing format (none / short)
- changing decimals and then the value in 'hide series'
- changing stat type (current / average)
- inspecting data (raw data comes in decimals, like 0.013, 0.13, 0.1453 etc.

**Related Issues and Links**

Screenshot showing the issue: https://d.pr/i/R9cHnw
Screenshot of pattern config: https://d.pr/i/fHN58x

Can you please help?

**Comment by yesoreyeram** [comment]
Seems issue related to https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/pull/100 . Fix will be applied soon
